name: FFT Daily Alert via Resend

on:
  push:
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  check_reviews:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use a suitable Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure requirements.txt includes pandas and any email sending library (e.g., resend)
        pip install -r automation_requirements.txt

    - name: Run review check script
      run: python ai_medreview/send_review_alerts.py
      env:
        # Define environment variables for your script, especially for secrets
        # You MUST add these as secrets in your GitHub repository settings
        # For example, go to Settings > Secrets and variables > Actions > New repository secret
        RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
