name: Send Monthly FFT Extraction Email

on:
  schedule:
    # Runs at 22:30 on the 3rd day of every month (UTC) for testing
    - cron: '30 22 3 * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install colorama

      - name: Run extractor and send email
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SENDER: ${{ secrets.SENDER }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          echo "Running extractor for previous month (calculated in script)"
          python ai_medreview/extractor.py
