[theme]
font="Inter:https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
baseFontSize=13
theme.baseFontWeight="400"
theme.headingFontWeights="h5"
theme.codeFontSize=16
# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#004768"

# Background color for your app
backgroundColor = "#ffffff"

# Secondary background color for your app
secondaryBackgroundColor = "#f4f4f5"

# Text color for your app
textColor = "#334155"

# Font for your app, choose between "sans serif", "serif", and "monospace"
linkColor="#344756"


[deprecation]
showPyplotGlobalUse = false

[server]
enableStaticServing = false
